apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "football-app.labels" . | nindent 4 }}
    app: result-service
    app.kubernetes.io/component: result-service
spec:
  selector:
    app: result-service
  ports:
    - port: {{ .Values.services.result.port }}
      targetPort: {{ .Values.services.result.port }}
