apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "football-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: secrets

type: Opaque
stringData:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | quote }}
  mysql-database: {{ .Values.secrets.mysqlDatabase | quote }}
  mysql-user: {{ .Values.secrets.mysqlUser | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | quote }}
