secrets:
  name: football-secrets
  mysqlRootPassword: qa-root
  mysqlDatabase: football_qa
  mysqlUser: qa
  mysqlPassword: qa

databaseUrl: mysql://qa:qa@mysql:3306/football_qa

ingress:
  enabled: true
  className: nginx
  host: final-project-app-qa.k8s
  path: /
  pathType: Prefix
