secrets:
  name: football-secrets
  mysqlRootPassword: prod-root
  mysqlDatabase: football_prod
  mysqlUser: prod
  mysqlPassword: prod

databaseUrl: mysql://prod:prod@mysql:3306/football_prod

ingress:
  enabled: true
  className: nginx
  host: final-project-app-prod.k8s
  path: /
  pathType: Prefix
