secrets:
  name: football-secrets
  mysqlRootPassword: root
  mysqlDatabase: football
  mysqlUser: app
  mysqlPassword: app

databaseUrl: mysql://app:app@mysql:3306/football

config:
  name: football-config
  playerServiceUrl: http://player-service:3001
  gameServiceUrl: http://game-service:3002
  teamServiceUrl: http://team-service:3003
  resultServiceUrl: http://result-service:3004
  httpTimeoutMs: "3000"
  maxResponseBytes: "1048576"
  bodyLimit: 1mb
  logLevel: info

mysql:
  image:
    repository: ghcr.io/romastelchenko/final-project-mysql
    tag: ""
  imagePullPolicy: Always
  port: 3306
  replicas: 1
  persistence:
    pvcName: mysql-pvc
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClassName: nfs-client
services:
  player:
    image:
      repository: ghcr.io/romastelchenko/final-project-player-service
      tag: ""
    imagePullPolicy: Always
    port: 3001
    replicas: 1
  game:
    image:
      repository: ghcr.io/romastelchenko/final-project-game-service
      tag: ""
    imagePullPolicy: Always
    port: 3002
    replicas: 1
  team:
    enabled: false
    image:
      repository: ghcr.io/romastelchenko/final-project-team-service
      tag: ""
    imagePullPolicy: Always
    port: 3003
    replicas: 1
  result:
    enabled: false
    image:
      repository: ghcr.io/romastelchenko/final-project-result-service
      tag: ""
    imagePullPolicy: Always
    port: 3004
    replicas: 1
  apiGateway:
    image:
      repository: ghcr.io/romastelchenko/final-project-api-gateway
      tag: ""
    imagePullPolicy: Always
    port: 3000
    replicas: 1
  frontend:
    image:
      repository: ghcr.io/romastelchenko/final-project-frontend
      tag: ""
    imagePullPolicy: Always
    port: 80
    replicas: 1
    apiGatewayUrl: http://api-gateway:3000

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /
  pathType: Prefix
