apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    {{- include "football-app.labels" . | nindent 4 }}
    app: mysql
    app.kubernetes.io/component: mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        {{- include "football-app.selectorLabels" . | nindent 8 }}
        app: mysql
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          imagePullPolicy: {{ .Values.mysql.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: mysql-database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: mysql-password
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-p{{ .Values.secrets.mysqlRootPassword }}"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-p{{ .Values.secrets.mysqlRootPassword }}"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
